// src/app/core/constants/navigation-items.ts
export interface NavigationItem {
  id: string; // Unique string ID (e.g., "nav-home")
  numId: number; // Numeric identifier
  label: string;
  path: string;
  dropDown: boolean;
  children?: NavigationItem[];
}

export const NAVIGATION_ITEMS: NavigationItem[] = [
  {
    id: 'nav-home',
    numId: 1,
    label: 'Home',
    path: 'Common/dashboard',
    dropDown: false,
  },
  {
    id: 'operations',
    numId: 2,
    label: 'Operations',
    path: 'booking',
    dropDown: true,
    children: [
      {
        id: 'nav-booking',
        numId: 2,
        label: 'Booking',
        path: 'booking',
        dropDown: false,
        children: [
          {
            id: 'nav-booking-register',
            numId: 1,
            label: 'Booking Register',
            path: 'booking/booking_register',
            dropDown: false,
          },
          {
            id: 'nav-booking-list',
            numId: 2,
            label: 'Booking List',
            path: 'booking/list',
            dropDown: false,
          },
          {
            id: 'nav-advance-booking-register',
            numId: 3,
            label: 'Advance Booking Register',
            path: 'advance_bookings',
            dropDown: false,
          },
          {
            id: 'nav-booking-order',
            numId: 4,
            label: 'Booking Order',
            path: 'bookingorder/manage_booking_orders',
            dropDown: false,
          },
          {
            id: 'nav-date-wise-bulk-booking-print',
            numId: 5,
            label: 'Date Wise Bulk Booking Print',
            path: 'date_wise_booking_print',
            dropDown: false,
          },
          {
            id: 'nav-bulk-booking-print-mahagoenkar',
            numId: 6,
            label: 'Bulk Booking Print (Mahagoenkar)',
            path: 'date_wise_booking_print_mahagoenkar',
            dropDown: false,
          },
          {
            id: 'nav-bulk-booking-print-aayush',
            numId: 7,
            label: 'Bulk Booking Print (Aayush)',
            path: 'date_wise_booking_print_aayush',
            dropDown: false,
          },
          {
            id: 'nav-bulk-booking-print-lokenath',
            numId: 8,
            label: 'Bulk Booking Print (Lokenath Express)',
            path: 'date_wise_booking_print_lokenath_express',
            dropDown: false,
          },
          {
            id: 'nav-marketing',
            numId: 9,
            label: 'Marketing',
            path: 'marketing/dashboard',
            dropDown: false,
          },
        ],
      },
      {
        id: 'nav-loading',
        numId: 3,
        label: 'Loading',
        path: 'loading',
        dropDown: false,
        children: [
          {
            id: 'nav-manifest-register',
            numId: 1,
            label: 'Manifest Register',
            path: 'manifest/manifest_register',
            dropDown: false,
          },
          {
            id: 'nav-manifest-transit-register',
            numId: 2,
            label: 'Manifest Transit Register',
            path: 'manifest/manifest_in_transit_register',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-register',
            numId: 3,
            label: 'Vehicle Register',
            path: 'vehicle/register/manage_vehicle_register',
            dropDown: false,
          },
          {
            id: 'nav-manage-loading-slips',
            numId: 4,
            label: 'Manage Loading Slips',
            path: 'loadingslip/manage_loading_slips',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-hire-register',
            numId: 5,
            label: 'Vehicle Hire Register',
            path: 'vehiclehire/vehicle_hire_register',
            dropDown: false,
          },
          {
            id: 'nav-local-vehicle-hire-register',
            numId: 6,
            label: 'Local Vehicle Hire Register',
            path: 'localVehicleHire/local_vehicle_hire_register',
            dropDown: false,
          },
          {
            id: 'nav-full-load-vehicle-hire-register',
            numId: 7,
            label: 'Full Load Vehicle Hire Register',
            path: 'vehiclehire/full_load_vehicle_hire_register',
            dropDown: false,
          },
          {
            id: 'nav-driver-register',
            numId: 8,
            label: 'Driver Register',
            path: 'driver/manage_drivers',
            dropDown: false,
          },
          {
            id: 'nav-petrol-pump-register',
            numId: 9,
            label: 'Petrol Pump Register',
            path: 'petrolpump/manage_petrol_pumps',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-vendors',
            numId: 10,
            label: 'Vehicle Vendors',
            path: 'vehiclevendors/manage_vehicle_vendors',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-expense',
            numId: 11,
            label: 'Vehicle Expense Managers',
            path: 'vehicleexpense/manage_vehicle_expenses',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-in-transit',
            numId: 12,
            label: 'Vehicle In Transit',
            path: 'ftlvehicletransit/manage_ftl_vehilce_in_transit',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-service',
            numId: 12,
            label: 'Vehicle Service',
            path: 'vehicleservice/manage_vehicle_services',
            dropDown: false,
          },
          {
            id: 'nav-manage-fuel-payment',
            numId: 12,
            label: 'Manage Fuel Payment',
            path: 'fuelpayment/manage_fuel_payments',
            dropDown: false,
          },
        ],
      },
      {
        id: 'nav-dispatch',
        numId: 4,
        label: 'Dispatch',
        path: 'dispatch',
        dropDown: false,
        children: [
          {
            id: 'nav-outstation-dispatch',
            numId: 1,
            label: 'Outstation Dispatch',
            path: 'outstation_despatch',
            dropDown: false,
          },
          {
            id: 'nav-dispatch-register-report',
            numId: 2,
            label: 'Dispatch Register Report',
            path: 'register-reports',
            dropDown: false,
          },
        ],
      },
      {
        id: 'nav-receive',
        numId: 5,
        label: 'Receive',
        path: '',
        dropDown: false,
        children: [
          {
            id: 'nav-unload-consignment',
            numId: 1,
            label: 'Unload Consignment',
            path: 'despatch/despatch_list',
            dropDown: false,
          },
          {
            id: 'nav-unload-consignment-multi-location',
            numId: 2,
            label: 'Unload Consignment (Multi Location)',
            path: 'unload/unload_list',
            dropDown: false,
          },
          {
            id: 'nav-lorry-arrival-register',
            numId: 3,
            label: 'Lorry Arrival Register',
            path: 'arival/arrival_list',
            dropDown: false,
          },
          {
            id: 'nav-vehicle-pending-payments',
            numId: 4,
            label: 'Vehicle Pending Payments',
            path: 'vehiclepayments/manage_pending_payments',
            dropDown: false,
          },
          {
            id: 'nav-lr-consignment-incoming-register',
            numId: 5,
            label: 'LR/Consignment Incoming Register',
            path: 'reports/lr_consignment_incoming_register',
            dropDown: false,
          },
          {
            id: 'nav-full-load-vehicle-pending-payments',
            numId: 6,
            label: 'Full Load Vehicle Pending Payments',
            path: 'vehiclepayments/full_load_vehicle_pending_payments',
            dropDown: false,
          },
          {
            id: 'nav-incoming-booking-register',
            numId: 7,
            label: 'Incoming Booking Register',
            path: 'booking/incoming_booking_register',
            dropDown: false,
          },
        ],
      },
      {
        id: 'nav-delivery',
        numId: 6,
        label: 'Delivery',
        path: 'delivery',
        dropDown: false,
        children: [
          {
            id: 'nav-gatepass-register',
            numId: 1,
            label: 'Gatepass Register',
            path: 'gatepass/gatepass_register',
            dropDown: false,
          },
          {
            id: 'nav-pending-gatepass-register',
            numId: 2,
            label: 'Pending Gatepass Register',
            path: 'gatepass/pending_gatepass_register',
            dropDown: false,
          },
          {
            id: 'nav-delivery-register',
            numId: 3,
            label: 'Delivery Register',
            dropDown: false,
            path: 'delivery_register',
          },
          {
            id: 'nav-godown-delivery',
            numId: 4,
            label: 'Godown Delivery',
            path: 'pending_delivery_list',
            dropDown: false,
          },
          {
            id: 'nav-full-load-delivery-register',
            numId: 5,
            label: 'Full Load Delivery Register',
            path: 'full_load_delivery_register',
            dropDown: false,
          },
          {
            id: 'nav-direct-deliveries',
            numId: 6,
            label: 'Direct Deliveries',
            path: 'quick_delivery_list',
            dropDown: false,
          },
          {
            id: 'nav-third-party-delivery-register',
            numId: 7,
            label: 'Third Party Delivery Register',
            path: 'doordelivery/door_delivery_register',
            dropDown: false,
          },
          {
            id: 'nav-door-third-party-delivery-pending-payments',
            numId: 8,
            label: 'Door/Third Party Delivery Pending Payments',
            path: 'doordeliverypayments/door_delivery_vehicle_pending_payments',
            dropDown: false,
          },
          {
            id: 'nav-barcode-delivery-register',
            numId: 9,
            label: 'Barcode Delivery Register',
            path: 'barcodedelivery/barcode_delivery_register',
            dropDown: false,
          },
        ],
      },
    ],
  },
  {
    id: 'nav-accounting',
    numId: 7,
    label: 'Accounting',
    path: '',
    dropDown: true,
    children: [
      {
        id: 'nav-accounts',
        numId: 1,
        label: 'Accounts',
        path: 'account_list',
        dropDown: false,
      },
      {
        id: 'nav-manage-purchases',
        numId: 2,
        label: 'Manage Purchases',
        path: 'manage_purchases',
        dropDown: false,
      },
      {
        id: 'nav-money-receipt',
        numId: 3,
        label: 'Money Receipt',
        path: 'manage_money_receipts',
        dropDown: false,
      },
      {
        id: 'nav-invoices',
        numId: 4,
        label: 'Invoices',
        path: 'invoices/manage_invoice',
        dropDown: false,
      },
      {
        id: 'nav-money-transfer-contra',
        numId: 5,
        label: 'Money Transfer (Contra)',
        path: 'accountVoucher/manage_account_vouchers/manage_invoice',
        dropDown: false,
      },
      {
        id: 'nav-debit-note-entry',
        numId: 6,
        label: 'Debit Note Entry',
        path: 'debitNotes/manage_debit_note_entries',
        dropDown: false,
      },
      {
        id: 'nav-credit-note-entry',
        numId: 7,
        label: 'Credit Note Entry',
        path: 'creditNotes/manage_credit_note_entries',
        dropDown: false,
      },
      {
        id: 'nav-pending-payments',
        numId: 8,
        label: 'Pending Payments',
        path: 'pendingpayments/pending_payment_management',
        dropDown: false,
      },
      {
        id: 'nav-payment-vouchers',
        numId: 9,
        label: 'Payment Vouchers',
        path: 'accountVoucher/manage_account_vouchers/manage_invoice',
        dropDown: false,
      },
      {
        id: 'nav-manage-sales',
        numId: 10,
        label: 'Manage Sales',
        path: 'sale/manage_sales',
        dropDown: false,
      },
      {
        id: 'nav-manage-expense',
        numId: 11,
        label: 'Manage Expense',
        path: 'expenses/manage_expenses',
        dropDown: false,
      },
      {
        id: 'nav-manage-expense',
        numId: 12,
        label: 'Manage Expense',
        path: 'expenses/manage_expenses',
        dropDown: false,
      },
      {
        id: 'nav-bulk-invoice-print',
        numId: 13,
        label: 'Bulk Invoice Print',
        path: 'invoices/bulk_invoice_print',
        dropDown: false,
      },
      {
        id: 'nav-manage-accounts-group',
        numId: 14,
        label: 'Manange Account Groups',
        path: 'accountGroup/account_group_register',
        dropDown: false,
      },
      {
        id: 'nav-journal-entry',
        numId: 15,
        label: 'Journal Extry',
        path: 'journal/manage_journal_entries',
        dropDown: false,
      },
      {
        id: 'nav-bulk-receive',
        numId: 16,
        label: 'Bulk Receive',
        path: 'bulkreceive/manage_bulk_received_amounts',
        dropDown: false,
      },
      {
        id: 'nav-bulk-payment',
        numId: 16,
        label: 'Bulk Payments',
        path: 'bulkpayment/manage_bulk_payments',
        dropDown: false,
      },
    ],
  },
  {
    id: 'nav-reports',
    numId: 8,
    label: 'Reports',
    path: 'reports/managereports',
    dropDown: false,
  },
  {
    id: 'nav-settings',
    numId: 9,
    label: 'Settings',
    path: 'settings/settingsmanagement',
    dropDown: false,
  },
];
